# Generated by Django 5.1.6 on 2025-02-26 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('calorie_goal', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cook_time', models.PositiveIntegerField(blank=True, help_text='Cook time in minutes', null=True)),
                ('instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_gram', models.FloatField(default=0)),
                ('protein_per_gram', models.FloatField(default=0)),
                ('fats_per_gram', models.FloatField(default=0)),
                ('carbohydrates_per_gram', models.FloatField(default=0)),
                ('cost_per_gram', models.FloatField(default=0)),
                ('grams_in_package', models.FloatField(blank=True, null=True)),
                ('calories_per_package', models.FloatField(blank=True, null=True)),
                ('protein_per_package', models.FloatField(blank=True, null=True)),
                ('fats_per_package', models.FloatField(blank=True, null=True)),
                ('carbohydrates_per_package', models.FloatField(blank=True, null=True)),
                ('cost_per_package', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('notes', models.TextField()),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.IntegerField(default=0)),
                ('total_fats', models.IntegerField(default=0)),
                ('total_carbohydrates', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.FloatField(blank=True, help_text='Default quantity in grams (optional)', null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='meals.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DailySubmissionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.FloatField()),
                ('cost_per_gram', models.FloatField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.dailysubmission')),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dishingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='meals.DishIngredient', to='meals.ingredient'),
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.FloatField()),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dishingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='usage',
            field=models.ManyToManyField(blank=True, to='meals.usage'),
        ),
    ]
