# Generated by Django 5.1.6 on 2025-02-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='dish',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, help_text='Cook time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_gram',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates_per_gram',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats_per_gram',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_gram',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.FloatField(blank=True, help_text='Default quantity in grams (optional)', null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='meals.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DailySubmissionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='meals.dailysubmission')),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dishingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='meals.DishIngredient', to='meals.ingredient'),
        ),
    ]
