# Generated by Django 5.1.6 on 2025-02-27 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_task_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcneEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('severity', models.IntegerField(choices=[(1, 'Clear'), (2, 'Almost Clear'), (3, 'Mild'), (4, 'Moderate'), (5, 'Severe')], default=3)),
                ('image', models.ImageField(upload_to='acne_images/')),
                ('notes', models.TextField(blank=True)),
                ('products_used', models.ManyToManyField(blank=True, to='meals.skinproduct')),
            ],
            options={
                'verbose_name_plural': 'Acne Entries',
                'ordering': ['-entry_date'],
            },
        ),
    ]
