# Generated by Django 5.1.6 on 2025-02-13 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_rename_description_dish_notes_remove_ingredient_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmission',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='total_carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='total_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='total_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='usage',
            field=models.CharField(default='default usage', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailysubmission',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailysubmission',
            name='submission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailysubmissioningredient',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.dailysubmission'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.FloatField()),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.dishingredient')),
            ],
        ),
    ]
