# Generated by Django 5.1.6 on 2025-02-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_skinproduct_acneentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_subtasks', to='meals.subtask'),
        ),
    ]
