# Generated by Django 5.1.6 on 2025-02-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_dailysubmission_total_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysubmission',
            name='usage',
        ),
        migrations.AddField(
            model_name='dailysubmission',
            name='usage',
            field=models.ManyToManyField(blank=True, to='meals.usage'),
        ),
    ]
