# Generated by Django 5.1.6 on 2025-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_remove_dailysubmission_usage_dailysubmission_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_gram',
            field=models.FloatField(default=0),
        ),
    ]
