# Generated by Django 5.1.6 on 2025-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_ingredient_cost_per_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmissioningredient',
            name='cost_per_gram',
            field=models.FloatField(default=0),
        ),
    ]
