# Generated by Django 5.1.6 on 2025-02-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_dailysubmissioningredient_cost_per_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
