# Generated by Django 5.1.6 on 2025-03-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_profile_dailycaloriegoal_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.profile')),
            ],
            options={
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
