# Generated by Django 5.1.6 on 2025-02-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_dailysubmission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates_per_package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats_per_package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='grams_in_package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_package',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
