# Generated by Django 5.1.6 on 2025-03-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_workoutpreset_presetexercise_workout_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetexercise',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='presetexercise',
            name='default_sets',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='presetexercise',
            name='max_reps',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='presetexercise',
            name='min_reps',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
