# Generated by Django 5.1.6 on 2025-02-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_ingredient_calories_per_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('calorie_goal', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
