# Generated by Django 5.1.6 on 2025-03-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_presetexercise_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmission',
            name='feeling_rating',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
