# Generated by Django 5.1.6 on 2025-03-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_task_completed_task_details_task_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.profile'),
        ),
    ]
