# Generated by Django 5.1.6 on 2025-03-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
