# Generated by Django 5.1.6 on 2025-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_habit_completion_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('whenever', 'Whenever')], default='daily', max_length=10),
        ),
    ]
