[phases.setup]
nixPkgs = ["...", "postgresql"]

# Skip migrations during build
[phases.build]
cmds = ["echo 'Skipping migrations during build'", "python manage.py collectstatic --noinput"]

# Run migrations only at startup
[start]
cmd = "bash -c 'python manage.py migrate --fake && python manage.py runserver 0.0.0.0:$PORT'"