databases:
  - name: mealplanner-db

services:
  - type: web
    name: mealplanner-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 mealplanner.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mealplanner-db
          property: connectionString

    healthCheckPath: /
    plan: free

    buildCommands:
      - python manage.py migrate