services:
  - type: web
    name: fawn
    region: us-west
    plan: free
    env: production
    build_command: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    start_command: "gunicorn mealplanner.wsgi:application"
    static_paths:
      - /static/: staticfiles/